venth/aws-adfs

aws_adfs/prepare.py

Needs to be a string since we call ast.parse_literal on it, but the
Click option is a switch, which results in a bool. Convert it to str
when storing.

ssl_verification must be a str

---

setup.py

Setup should not require pytest-runner, just tests. Fixes pip not properly cataloguing install requirements based on information available from pypi.

Move pytest-runner out of setup-requires

---

aws_adfs/authenticator.py
aws_adfs/html_roles_fetcher.py
aws_adfs/login.py
aws_adfs/prepare.py
test/test_config_preparation.py
test/test_fetch_html_encoded_roles.py

As per issue #18 - this is the kind of work around I require. My parent company provide the SSO for all its child companies, and as a result, the urn is different for each. Not sure if this is the correct way for them to do this, but it is. So it required me to edit he hard coded value in the library.

Added extra option "--provider-id" 

---

aws_adfs/_duo_authenticator.py

This fixes #42 - Parsing error when trying to login to Duo MFA to parse out the duo host and signature from the ADFS response page.
This was done in a backwards compatible fashion so it at first tries the existing parsing logic, and if that fails (try/catch) it falls back to trying the new way.  It could be better, but works great for us.  Improve if desired.
Thanks for this tool, works great (now)!

#42 - Bug in parsing Duo host and signature, backwards compatible

---

aws_adfs/html_roles_fetcher.py
setup.py

It recently came to my attention that the current use of requests-negotiate-sspi on Windows hosts was causing the module to fail if Negotiate authentication failed. This was due to our user-agent spoofing causing ADFS to continue redirecting us through the Integrated Windows Authentication (IWA) page's 401 response, since it only supports Negotiate auth - not form input.
This change passes the username and password through to the auth module, which lets Windows handle authentication properly in cases where Kerberos credentials are not available or are not accepted by the ADFS host.

Fix Negotiate auth on non-domain-joined Windows hosts

---

aws_adfs/login.py

The enanchment #67 could be solved by this pull request.
The role_arn is already a configuration parameter. The parameter value is available in the configuration object so if the value is present as parameter just set it. The role_chooser works as aspected and the role_arn is selected.
Tested with an account with multiple roles. 
Hope this help.

Role arn as parameter

---

aws_adfs/_duo_authenticator.py

The app would crash when calling a phone.

Allow phone call authentication

---

aws_adfs/authenticator.py
aws_adfs/login.py
aws_adfs/roles_assertion_extractor.py

This could be useful for debugging and configuring unknown (or broken) 2FA providers

Allow to specify SAML response from local file

---

aws_adfs/authenticator.py
aws_adfs/html_roles_fetcher.py
aws_adfs/login.py

Added option to disable SSPI authentication, which may not work in some environments.
This is similar to avoidik's pull request, but without the double negation. Mimics how ssl-verification is flagged.

Added flag for disabling Kerberos SSO authentication via SSPI

---

aws_adfs/_duo_authenticator.py

Save the session cookies after a DUO authentication request. Prevents having to repeat the MFA login process when not required.

Save duo session cookies

---

aws_adfs/_azure_mfa_authenticator.py
aws_adfs/authenticator.py

This commit adds support for Azure MFA authentication. The way this auth method works is an out-of-band message or phone call is sent to a user's configured mobile device. The user then authorizes the login attempt and the request proceeds.
This is very similar to the existing Symantec VIP authenticator, except no extra information is forwarded to the server.
As the process is very similar to the Symantec method I have reused a lot of the code from that module.
I have tested this method and did not encounter any issues. In the event of a timeout (or any other failure). The roles_assertion_extractor will find and print the error.

Add support for Azure MFA Server

---

aws_adfs/_duo_authenticator.py

Without this change, authentication initiation failures results in the following obscure message:
```
```Traceback (most recent call last):
File "/home/nsd/.pyenv/versions/aws-adfs/bin/aws-adfs", line 10, in <module>
sys.exit(cli())
File "/home/nsd/.pyenv/versions/2.7.16/envs/aws-adfs/lib/python2.7/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/home/nsd/.pyenv/versions/2.7.16/envs/aws-adfs/lib/python2.7/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/home/nsd/.pyenv/versions/2.7.16/envs/aws-adfs/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/nsd/.pyenv/versions/2.7.16/envs/aws-adfs/lib/python2.7/site-packages/click/core.py", line …

Fix Duo authentication initiation failure messages

---

aws_adfs/login.py
aws_adfs/reset.py

AWS CLI gets predefined profile from AWS_DEFAULT_PROFILE if defined.
Otherwise profile "default" is used.
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html#using-profiles
This patch adds the same behavior as AWS CLI.

Respect AWS_DEFAULT_PROFILE if defined

---

aws_adfs/_azure_cloud_mfa_authenticator.py
aws_adfs/authenticator.py

This PR adds support for AzureMfaAuthentication AuthMethod that is used in the Azure MFA SAAS/Cloud version.
It is based on the _azure_mfa_authenticator code (that supports the AzureServerMfaAuthentication AuthMethod). Instead, this code polls every five seconds (up to max 60) until it gets a valid SAMLResponse.
It is tested to work along with push notifications to the Microsoft Authenticator app for approval.

Add support for AzureMfaAuthentication

---

aws_adfs/_symantec_vip_access.py
aws_adfs/authenticator.py
aws_adfs/html_roles_fetcher.py
aws_adfs/login.py
aws_adfs/prepare.py
test/test_authenticator.py
test/test_config_preparation.py
test/test_fetch_html_encoded_roles.py

Changes covered:
- Enhanced Symantec Code to handle both the 'old' and 'new' Auth Methods.  I am unable to find any documentation on why or when these values changed, but our system still uses the 'old' ones. See [here](https://github.com/venth/aws-adfs/pull/96) for background.  This should handle both, but has **only been tested against the old**
- SSPI Fixes:
- Handle SSPI like other config options (store in profile, etc)
- Only set user-agent header when SSPI is enabled.  In our environment (No SSPI), this causes a 401.
- As a side-effect of the config change, this [call](https://github.com/venth/aws-adfs/blob/5c9852ebb693e9f0fe90338829aff207aa456a84/aws_adfs/login.py#L139) correctly uses sspi.  Without this change, the call is always made with sspi enabled, which causes an exception. …

Handle sspi like other config options

---

setup.py

Python 3.4 jobs fail at setup time no matter what: https://travis-ci.org/venth/aws-adfs/jobs/575755915
```
$ pip install --editable .
Obtaining file:///home/travis/build/venth/aws-adfs
Collecting lxml (from aws-adfs==1.17.0+2.g9784f83)
Downloading https://files.pythonhosted.org/packages/e1/f5/5eb3b491958dcfdcfa5daae3c655ab59276bc216ca015e44743c9c220e9e/lxml-4.4.0.tar.gz (4.5MB)
Complete output from command python setup.py egg_info:
This lxml version requires Python 2.7, 3.5 or later.
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-d_wprq64/lxml/
The command "pip install --editable ." failed and exited with 1 during .
Your build has been stopped.
```
Support for python 3.4 was removed in lxml 4.4.0: …

lxml 4.4.0 dropped support for python 3.4

---

README.md
aws_adfs/_duo_authenticator.py
aws_adfs/commands.py
aws_adfs/html_roles_fetcher.py
setup.py
test/test_fetch_html_encoded_roles.py

This PR adds support for FIDO/U2F to Duo authentication.
If Duo reports U2F is supported for the user, it is used concurrently to the default authentication method.
~It's a rough draft that works but needs cleanup, hence the _WIP_.
I opened the PR now to get early feedback if possible.~
~Right now, if Duo reports U2F is supported for the user, only that authentication method is used.~
Example usage shown here: https://github.com/venth/aws-adfs/pull/127#issuecomment-534110072
Tested in USB mode with:
- Yubikey Neo
- Yubikey 5 NFC
- Yubikey 5 Nano
It should support NFC mode too but that is not tested yet.
TODO:

Add FIDO/U2F support to Duo authentication

---

aws_adfs/html_roles_fetcher.py
setup.py
test/test_fetch_html_encoded_roles.py

`LWPCookieJar` has an issue on Windows when cookies have `expires` dates too far in the future and they are converted from timestamp to datetime.
With aws-adfs 1.17.0:
```
PS C:\> & C:\aws-adfs\Scripts\pip install aws-adfs==1.17.0
PS C:\> & C:\aws-adfs\Scripts\aws-adfs login --region=eu-west-1 --adfs-host=sso.mydomain.net --ssl-verification --session-duration=3600 --no-sspi                                       2019-08-23 11:05:06,588 [authenticator authenticator.py:authenticate] [3220-MainProcess] [7008-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
Password:
Waiting for additional authentication
Going for aws roles
Traceback (most recent call last):
File "C:\aws-adfs\Scripts\aws-adfs-script.py", line 11, in <module> …
```

Use MozillaCookieJar to support cookies with "expires" far in the future on Windows

---

.travis.yml

This adds 3.6, 3.7 and 3.8-dev to the list of tested python versions.
Python 3.4 jobs fail, fix is in #130.

Run tests with python 3.6, 3.7 and 3.8-dev

---

aws_adfs/_duo_authenticator.py
aws_adfs/authenticator.py
aws_adfs/html_roles_fetcher.py
aws_adfs/login.py
aws_adfs/prepare.py
test/test_authenticator.py
test/test_config_preparation.py

This PR adds `--u2f-trigger-default`/`--no-u2f-trigger-default` options to determine whether to trigger the default authentication method when U2F is available (only works with Duo for now).
TODO:

Add options to trigger or not the default authentication method when U2F is available

---

aws_adfs/_duo_authenticator.py

This PR fixes the `AttributeError: 'generator' object has no attribute 'append'` that happens on python3 when the `pyscard` package is installed.

Fix AttributeError: 'generator' object has no attribute 'append' on python3

---

setup.py

Just published [fido2 0.8.0, quickly followed by 0.8.1](https://github.com/Yubico/python-fido2/releases/tag/0.8.1), is a breaking release.
Current implementation of U2F support in aws-adfs no longer works (did not investigate yet).
Until compatibility is achieved, pin that dependency to `< 0.8.0`.

Pin fido2 dependency to < 0.8.0 as it is a breaking release

---

aws_adfs/_duo_authenticator.py
setup.py

This PR updates aws-adfs for compatibility with the recently released [fido2 0.8.1](https://github.com/Yubico/python-fido2/releases/tag/0.8.1), which is a breaking release.
The `timeout` parameter of `U2FClient.sign()` was renamed to `event` in fido2, see https://github.com/Yubico/python-fido2/commit/4c48977173fd32f70e61f518c7624558ffe54b9c#diff-570624f6ea4a71fef9e9cfcc8fe7b1a0R244
Supersedes https://github.com/venth/aws-adfs/pull/140

U2F: fido2 v0.8.1 compatibility (U2FClient.sign timeout renamed to event)

---

aws_adfs/html_roles_fetcher.py
setup.py

I was trying to use this project as a replacement for our own in-house code that integrates AWS/ADFS in a less portable way. One thing I noticed though is that your code doesn't seem to support Kerberos logins on Linux.
Looking through our code we used `requests_kerberos` to achieve this so I quickly hacked it into the codebase in place of `requests-negotiate-sspi` and I managed to get it work.
`requests_kerberos` does support Windows as well (using https://github.com/mongodb-labs/winkerberos) so in theory this could be required on all platforms, however I'm not sure if there's anything `requests-negotiate-sspi` does that `winkerberos` via `requests_kerberos` doesn't.
Obviously the PR is incomplete as it stands but what direction would you like to take here?
This would probably then fix …

Kerberos support

---

aws_adfs/_duo_authenticator.py

This PR allows users without any preferred factor or device configured to still use U2F.
Without this change, the following error occurs in such a configuration:
```
$ aws-adfs --version
1.20.0
$ aws-adfs login
Traceback (most recent call last):
File "/usr/local/bin/aws-adfs", line 8, in <module>
sys.exit(cli())
File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line …
```

Duo: support U2F with no preferred factor or device configured

---

README.md

This PR documents the new libkrb5-dev system dependency introduced by #144 for pykerberos .
On Ubuntu, without `libkrb5-dev`, installation fails with:
```
Collecting aws-adfs==1.21.0
Downloading https://files.pythonhosted.org/packages/7f/7b/d1f893d8f523137a412ffc86b82b6709fd03904f000358b2e6c6e121ad7e/aws-adfs-1.21.0.tar.gz (52kB)
100% |████████████████████████████████| 61kB 993kB/s
Collecting boto3>=1.9.6 (from aws-adfs==1.21.0)
Downloading https://files.pythonhosted.org/packages/39/8b/250778bc5fd4b9a91d7916f8729b346931be419052130548617139247ba6/boto3-1.10.41-py2.py3-none-any.whl (128kB)
100% |████████████████████████████████| 133kB 1.3MB/s
Collecting botocore>=1.12.6 (from aws-adfs==1.21.0)
Downloading https://files.pythonhosted.org/packages/49/e0/a9a53656126a635120c0f7eaee3ff3b26a4a08596 …
```

Document new libkrb5-dev system dependency for pykerberos

---

README.md
aws_adfs/html_roles_fetcher.py
aws_adfs/login.py
aws_adfs/prepare.py

This PR changes the default value to the `--sspi` parameter to `False` on non-Windows systems as suggested by https://github.com/venth/aws-adfs/pull/144#issuecomment-567127634

Default SSPI to True on Windows only, False otherwise

---

aws_adfs/account_aliases_fetcher.py

The account_aliases function was sending username and password to AWS.

Fix username and password disclosure

---

aws_adfs/html_roles_fetcher.py

Commit 7108dea5 has broken authentication with stored cookies on
non-windows system. Fixed by this PR.

Fix authentication with cookies on non-windows system.

---

aws_adfs/html_roles_fetcher.py
test/test_fetch_html_encoded_roles.py

The `AuthMethod` parameter of the signon page is set to the value of provider_id. Which is `urn:amazon:webservices` by default. After enabling ADFS DeviceAuthentication signons are failing.  Setting the `AuthMethod` parameter to `FormsAuthentication` fixes the issue.

Change `AuthMethod` parameter to `FormsAuthentication`

---

README.md
aws_adfs/login.py

Adds support for non-public AWS regions (e.g. GovCloud).
Tested against us-gov-west-1 and us-gov-east-1.
Fixes venth#102

Add support for non-public AWS regions (e.g. GovCloud)

---

aws_adfs/_duo_authenticator.py

To avoid needing to set default Duo default authentication method, make aws-adfs tool ask for the method to use.
If Duo default authentication method is set (no change):
```
$ aws-adfs login --adfs-host="<host>" --session-duration 3600 
Waiting for additional authentication
Triggering authentication method: 'Duo Push'
```
If Duo default authentication method is not set:
```
$ aws-adfs login --adfs-host="<host>" --session-duration 3600 
Username: 	
Password: 
Waiting for additional authentication
No default authentication method configured.
Please enter your desired authentication method (Ex: Duo Push): Duo Push
Triggering authentication method: 'Duo Push'
```
If Duo default authentication method is not set, invalid …

Ask for authentication method if there is no default method set in Duo Security settings

---

aws_adfs/_duo_authenticator.py

This PR aims to resolve #157.
The issue was introduced by #127 : https://github.com/venth/aws-adfs/pull/127/files#diff-0584fbc181c07f609204d3aa5779348fR482

Always return the same number of values from _initiate_authentication()

---

.gitignore
.travis.yml

Replace python version 3.8-dev by 3.8 and add 3.9-dev.
We may want to drop 3.4 and maybe even 2.7 at some point, but there's no real gain right now. Maybe later if a cleanup or refactoring is considered at some point.
See https://devguide.python.org/#status-of-python-branches for officially supported python branches.

Add python 3.9-dev support

---

README.md
aws_adfs/login.py
test/test_credential_process_json.py

Enable full support for the AWS Credential profile credential process as outlined in [Sourcing External Credentials](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html).
This Pull Request adds the following items to the JSON output format to support the credential process integration:
- Version: 1
- Expiration: _ISO8601 formatted timestamp of the expiration timestamp (current time + session duration)_
This could then be integrated into the AWS Credentials file as follows:
```
[example-role-ue1]
credential-process=aws-adfs login --region=us-east-1 --role-arn=arn:aws:iam::1234567891234:role/example-role --adfs-host=adfs.example.com --stdout
```
Closes #112

Feature credential process

---

.gitignore
.travis.yml
test/test_assertion_extractor.py

Replace python version 3.8-dev by 3.8 and add 3.9-dev.
We may want to drop 3.4 and maybe even 2.7 at some point, but there's no real gain right now. Maybe later if a cleanup or refactoring is considered at some point.
See https://devguide.python.org/#status-of-python-branches for officially supported python branches.
Replaces #165 that was merged too soon: https://github.com/venth/aws-adfs/pull/165#issuecomment-653537135

Add python 3.9 support

---

.github/workflows/build.yml
aws_adfs/_duo_authenticator.py

Duo can be configured to not request MFA when connections come from specific IP addresses.
When that occurs, it directly bypasses MFA and returns the authentication cookie.
Without this PR, the following error occurs when Duo bypasses MFA:
```
2020-07-21 13:29:26,882 [authenticator authenticator.py:authenticate] [569451-MainProcess] [139864343611200-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
Username: me@mydomain.com
Password: 
2020-07-21 13:29:39,260 [authenticator authenticator.py:authenticate] [569451-MainProcess] [139864343611200-MainThread] - ERROR: Cannot extract saml assertion. Re-authentication needed?
This account does not have access to any roles
```
This has been tested by a …

Support Duo bypassing MFA requests

---

.github/workflows/build.yml

```
Version 3.4 with arch x64 not found The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
See https://github.com/venth/aws-adfs/pull/190/checks?check_run_id=3662149213

Github Actions no longer supports python 3.4

---

.github/workflows/build.yml

Python 3.9 wheels are now available from PyPI: https://pypi.org/project/lxml/#files

Compiling lxml from source is no longer needed with python 3.9

---

.github/workflows/build.yml
pyproject.toml

This PR automates the publishing of source and binary distribution packages to:
- https://test.pypi.org for all builds,
- https://pypi.org for tagged releases only.
Building those source and binary dists is now done via [poetry](https://github.com/python-poetry/poetry) [which implements](https://github.com/python-poetry/poetry-core) [PEP517](https://www.python.org/dev/peps/pep-0517/), e.g. locally:
```
pipx install poetry
poetry build
poetry publish
```
For more context, read:
* https://snarky.ca/what-the-heck-is-pyproject-toml/
* https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
* https://python-poetry.org/docs/cli/#build
* https://python-poetry.org/docs/cli/#publish

Automate PyPI publishing with poetry PEP517 built dists

---

.github/workflows/build.yml
poetry.lock
pyproject.toml

This reinstates the behavior from `setup.py` before [migration to poetry](#194):
```
if system() == 'Windows':
install_requires.append('requests-negotiate-sspi>=0.3.4')
else:
install_requires.append('requests_kerberos')
```
https://github.com/venth/aws-adfs/pull/144/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R29-R32

Depend on requests-negotiate-sspi on Windows. On other platforms, depend on requests-kerberos and pykerberos.

---

aws_adfs/login.py

Issue #180
--printenv contains shell commands suitable for sourcing into the current environment. The extra summary information that's included breaks this use case.
This PR removes the summary information when using --printenv.

printenv excludes summary to be shell readable

---

README.md
aws_adfs/login.py
aws_adfs/prepare.py
test/test_config_preparation.py

This allows to login with:
```
aws-adfs login --username-password-command='echo "{\"username\": \"myusername\", \"password\": \"myusername\"}"' --region=eu-west-3 --adfs-host=myadfshost
```
This new method has the main advantage over the other methods (stdin, env, authfile) that if the cached ADFS cookie is still valid, the command used to retrieve username and password is not invoked.
This is mostly desired when that command is expensive and/or requires interaction (e.g. gopass with USB yubikey).
Concrete usage example with gopass:
```
aws-adfs login --username-password-command='echo "{\"username\": \"myusername\", \"password\": \"$(gopass show -o mygopasssecret)\"}"' --region=eu-west-3 --adfs-host=myadfshost
```
TODO:

Add `--username-password-command` to read username and password from the output of a shell command

---

README.md
aws_adfs/login.py
poetry.lock
pyproject.toml

This PoC implements the generation of AWS web console sign-in URLs as described in https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_enable-console-custom-url.html
Note: maybe this should not be integrated in aws-adfs but rather make it in another independent tool.
Resolves #143.
TODO:

Print AWS web console sign-in url

---

.github/dependabot.yml
.github/workflows/build.yml
README.md
aws_adfs/_duo_authenticator.py
aws_adfs/authenticator.py
aws_adfs/helpers.py
aws_adfs/html_roles_fetcher.py
aws_adfs/login.py
aws_adfs/prepare.py
poetry.lock
pyproject.toml
test/test_authenticator.py
test/test_config_preparation.py

Resolves #208 
- Switch from Duo U2F to WebAuthn
- Introduce trace_http_request helper function
Reference documentation used to implement this:
- https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#authenticatorGetAssertion
- https://w3c.github.io/webauthn/#sctn-usecase-authentication

Switch from U2F to WebAuthn for DUO authentication

---

aws_adfs/_rsa_authenticator.py

The RSA token might be composed of the combination of a rotating 6-digits code generated by a device, and a user-chosen PIN. The PIN is considered as secret. The rotating code can be reused for 30s/1min so it shouldn't be displayed either. Overall this field should be hidden.

Hide RSA token

---

aws_adfs/login.py

https://github.com/venth/aws-adfs/issues/234
truncating the file prevents trailing characters from breaking a cache load.

Adding truncate flag when opening the credential cache file.

---

aws_adfs/login.py

Disable cache if `role_arn` is not provided

---

pyproject.toml

Quick workaround for aws-adfs #243
I'm not at all sure this is sufficient, just wanted to provide a starting point.

Pin fido2 to below 1.0.0

---

aws_adfs/_duo_authenticator.py
aws_adfs/_duo_universal_prompt_authenticator.py

This PR fixes an issue when the 'transports' field is missing from the WebAuthn challenge.
It also fixes a regression with CTAP1 devices (e.g. Yubikey NEO) which have no `extensionResults` in assertion response since fido2 v1.0.0.

Tolerate missing 'transports' key from WebAuthn challenge, and fix regression with CTAP1 device since fido2 1.0.0

---

aws_adfs/_duo_universal_prompt_authenticator.py
pyproject.toml

When [Duo Verified Push MFA](https://duo.com/blog/verified-duo-push-makes-mfa-more-secure) is enabled, a verification code is requested to be entered in the Duo mobile application.
With this change, the verification code is displayed in aws-adfs normal output (on stderr), e.g.:
```
[...]
Waiting for additional authentication
Triggering authentication method: 'Duo Push' with 'phone1'
Duo Verified Push MFA code: 123456
[...]
```
PS: users of other Duo authentication methods like Phone Call or WebAuthn are not concerned by this change.

Add support for Duo Verified Push MFA

---

aws_adfs/login.py
aws_adfs/prepare.py
aws_adfs/role_chooser.py
test/test_config_preparation.py
test/test_role_chooser.py

See issue [342](https://github.com/venth/aws-adfs/issues/342)
Allow enforcing of the provided role_arn. In order to be backwards compatible default to False. So this behavior is opt-in.

feature: Allow enforcement role_arn config variable

---

.github/workflows/build.yml

PyPI.org was in maintenance when 2.6.1 was released, so publishing to it failed:
```
Publishing aws-adfs (2.6.1) to PyPI
- Uploading aws-adfs-2.6.1.tar.gz 0%
- Uploading aws-adfs-2.6.1.tar.gz 100%
UploadError
HTTP Error 403: Read-only mode: Uploads are temporarily disabled.
at /opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/poetry/publishing/uploader.py:216 in _upload
212│                     self._register(session, url)
213│                 except HTTPError as e:
214│                     raise UploadError(e)
215│ 
→ 216│             raise UploadError(e)
217│ 
2[18](https://github.com/venth/aws-adfs/actions/runs/3345574657/jobs/5541375181#step:9:19)│     def _do_upload(
2[19](https://github.com/venth/aws-adfs/actions/runs/3345574657/jobs/5541375181#step:9:20)│ …
```

Do not error if release already exists in test.pypi.org

---

README.md
aws_adfs/_azure_cloud_mfa_authenticator.py
aws_adfs/authenticator.py
aws_adfs/login.py
aws_adfs/prepare.py

This PR aims to allow multiple forms of MFA on Azura Cloud.
Currently, the solution polls the page and cheks for a SAML token, which will be provided if authentication happened externally, e.g. via Microsoft Authenticator app or via a phone call.
But other options for authentication is currently missing.
Verification codes can also be supplied to the page request, for authentication. For example OTP 6-digit codes or SMS codes.
With this PR, I have implemented support for both methods.
The solution will now read the MFA intruction string and print it. It will check if there is an input field for a verification code and prompt the user for it.
If it is not found, it will still poll as the current solution will.
If the verification code is given, the solution only needs to make a request …

Add support for verification codes on Azure Cloud MFA

---

aws_adfs/_azure_cloud_mfa_authenticator.py

Solves https://github.com/venth/aws-adfs/issues/371
Add support for number matching in Microsoft Authenticator app, by printing the number found in "validEntropyNumber", if it exists.
Will print in the command line, and when entered, login succeeds.

Add support for number matching in Microsoft Authenticator app

---

aws_adfs/_duo_universal_prompt_authenticator.py

In some cases, it resolves issues similar to #355, but may break Windows features like SSPI/Kerberos, hence the draft status.

Use Linux user-agent string to work-around Duo permission denied errors: `{"stat": "FAIL", "message_enum": 7, "data": {}}`

---

aws_adfs/_duo_authenticator.py
aws_adfs/_duo_universal_prompt_authenticator.py
aws_adfs/account_aliases_fetcher.py

fix: drop user-agent header from requests as it only seems to cause issues, especially with Duo

---

README.md
aws_adfs/_rsa_authenticator.py
aws_adfs/_symantec_vip_access.py
aws_adfs/authenticator.py
aws_adfs/login.py
aws_adfs/prepare.py
aws_adfs/run_command.py
test/test_config_preparation.py

add support for `mfa_token` env var and `--mfa-token-command` arg
fixes https://github.com/venth/aws-adfs/issues/174
I am unable to get `--stdin` to correctly accept a username and password when using symantec auth, even with the stock `2.9.1a0`, so that part of the issue request is not supported.
mfa tokens seem too transient to me to be suitable for an authfile, so that's also not supported.

add support for mfa_token env and mfa-token-command

---

aws_adfs/_duo_universal_prompt_authenticator.py

Changing re.sub in line 147 of this file to look for ANY digit in front of the "v" part. 
We ran into an issue in our environment because the original code here was looking for "v4" and our DUO setup was returning "v3", so this replacement never happened and resulted in a malformed URL leading to 403 responses from the DUO server.

Fix for DUO Universal Prompt authentication
